services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/#{DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
    ports:
      - "8080:8080"
    secrets:
      - source: db_password
        target: /etc/taskvault/spring/datasource/password
      - source: jwt_issuer
        target: /etc/taskvault/app/jwt/issuer
      - source: jwt_key
        target: /etc/taskvault/app/jwt/key
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:9.7.0-oraclelinux9
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "3306:3306"
    secrets:
      - db_root_password
      - db_password
    healthcheck:
        test: mysqladmin ping
        timeout: 20s
        retries: 10

secrets:
  db_root_password:
    file: secrets/db_root_password.txt
  db_password:
    file: secrets/db_password.txt
  jwt_issuer:
    file: secrets/jwt_issuer.txt
  jwt_key:
    file: secrets/jwt_key.txt
