# Sempre executa comandos DDL de criação das tabela do banco de dados
spring.sql.init.mode=always
# Nível de log da aplicação
logging.level.root=${log_level:info}
# Validade do JWT em segundos
app.jwt.expiration-seconds=14400
