# Desabilita banner do Spring na inicialização da aplicação
spring.main.banner-mode=off
# Importação da propriedade com senha do banco de dados e credenciais
# para emissão de JWT
spring.config.import=optional:configtree:/etc/taskvault/*/
